java:
  runtime:
    version: 17
server :
  port : 8088
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  messages :
    basename: lang/messages
    encoding : UTF-8
  profiles:
    active: dev