spring:
  config:
    activate:
      on-profile:
        - heroku
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: ${DATASOURCE_DRIVER}
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:none}
    properties:
      hibernate:
        dialect: ${JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.MySQL8Dialect}
        format_sql: ${JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}
    show-sql: ${JPA_SHOW_SQL:true}